### ISSUE TITLE
Add field for additional additional child tax credit (Lee-Rubio)

### ISSUE THREAD

**Issue by Amy-Xu** [OpenSourcePolicyCenter/webapp-public#103]
New field for this credit needs to be added to TaxBrain input page due to this [PR](https://github.com/open-source-economics/Tax-Calculator/pull/453).

<img width="413" alt="screen shot 2015-11-18 at 11 24 44 am" src="https://cloud.githubusercontent.com/assets/10549597/11246794/41341118-8de7-11e5-8a28-e2eb5b6caaed.png">

@MattHJensen Maybe in the section right below current additional child tax credit?

**Comment by MattHJensen** [comment]
Note that "Additional additional child tax credit (Lee-Rubio)" would be a new subsection header. 

@Amy-Xu, the name that is displayed for the parameter will be pulled from the long_name attribute in current_law_policy.json. So rather than "Credit amount for each qualify child", if the webapp team implemented this right now, the name would show up on the webapp as "Partially refundable child tax credit". Perhaps the long_name in current_law_policy.json should instead be "Additional additional child tax credit amount per qualifying child". And then the meta data should specify any additional information (like where the qualification rules come from for instance). 

> @MattHJensen Maybe in the section right below current additional child tax credit?

sounds good to me.

**Comment by Amy-Xu** [comment]
@MattHJensen Will open a PR to modify the meta data shortly. Thanks!

**Comment by Amy-Xu** [comment]
Already on TaxBrain. Closing.
