### ISSUE TITLE
Sidebar extends over footer

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/webapp-public#184]
The sidebar on TaxBrain is extending over the footer.  Relatedly, the link to run the model is not available on the screen (since it's at the bottom of the sidebar, it does not show up on the screen).  See screenshot below.  My browser resolution is 1280x800.

![taxbrain_ss](https://cloud.githubusercontent.com/assets/10715924/13709174/18265638-e778-11e5-967b-e318f95ec8a4.png)

CC: @mistakevin

**Comment by jdebacker** [comment]
FYI, I'm still

**Comment by talumbau** [comment]
yes this issue is still live. @mistakevin proposed this fix: https://github.com/OpenSourcePolicyCenter/webapp-public/pull/185

but, as I mentioned on his PR, I did not see an improvement. Kevin will be offline this week, so I'm wondering if I need another front-end dev to look at this. One work-around I have found is to make the font size smaller on the page. On Mac, this is accomplished with <Command + '-' key>. In other words, holding the Command key and then hitting the minus key. Similarly, to make the font size bigger, one can do 'hold Command key and hit plus'. This is just a work around until Kevin or another Bootstrap developer can look more closely.
