### ISSUE TITLE
changes to inflation indexing not affecting results

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#193]
When I change the cpi inflation buttons on the TaxBrain static input page, it doesn't affect results. 

See http://www.ospc.org/taxbrain/1587/ in which I turned off the personal exemption inflation button. 

This should be high priority. 

cc @talumbau @mistakevin

**Comment by talumbau** [comment]
When I re-run 1587 (hit edit parameters and submit), the `user_mods` given to the worker nodes is:

```
  user_mods is  {'_II_em_cpi': False, '_ID_BenefitSurtax_Switch': [[True, True, True, True, True, True, True]]} 
```

which seems correct (the addition of `_ID_BenefitSurtax_Switch` is a quirk in the interface and doesn't change anything since those are the default settings). I will run locally and try to understand why changing this switch does not create a delta if baseline vs. reform.

**Comment by MattHJensen** [comment]
@Amy-Xu, could you also please investigate locally w tax-calculator?

**Comment by Amy-Xu** [comment]
Locally it seems fine to me. I used `{2015:{'_II_em_cpi': False}}` as reform. Here're the baseline and reform diagnostic table I got.

Baseline: 
<img width="542" alt="screen shot 2016-03-14 at 1 01 50 pm" src="https://cloud.githubusercontent.com/assets/10549597/13752440/0dc812d4-e9e5-11e5-9618-9ab52f75933f.png">

Reform:
<img width="542" alt="screen shot 2016-03-14 at 1 02 00 pm" src="https://cloud.githubusercontent.com/assets/10549597/13752448/123501c4-e9e5-11e5-97b0-69cea44106a1.png">

**Comment by talumbau** [comment]
@Amy-Xu, yes I get a similar result, although, I used a bit more "low tech" technique and I started in 2016. I just manually called the `create_dfiference_table` on the two calculator after advancing in time. For 2016 there was no difference, but I advanced until 2019 and saw an expected difference. Here is my notebook:

https://anaconda.org/ospc/ii_em_cpi_notebook/notebook

I will manually run dropq and see what I get from that.

**Comment by talumbau** [comment]
I discovered the problem. Before processing, we separate out parameters into three groups: parameters for Behavior, Growth, or Policy. The allowed parameter names are based on the set returned by `default_data` here:
https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/parameters_base.py#L21

The `_cpi` flags are not a "real" parameter, per se, as they are modifiers of actual parameters. Therefore, they get filtered out. This will be a chande in `dropq`. I can add logic that says: if the parameter ends in `_cpi`, if the root of the name exists as an actual parameter name, allow it.

I wonder if we should do something like "if the parameter name is unknown (i.e. not in the set of Behavior, Growth, or Policy parameter) raise an error because clearly something is wrong." @MattHJensen what do you think of this idea? It would have caught this bug instead of silently removing an "unknown" parameter.

**Comment by MattHJensen** [comment]
Ahh. I see. That makes sense. 

> I wonder if we should do something like "if the parameter name is unknown (i.e. not in the set of Behavior, Growth, or Policy parameter) raise an error because clearly something is wrong."

Yes, this sounds good.

**Comment by talumbau** [comment]
closed via https://github.com/OpenSourcePolicyCenter/dropQ/pull/51
