### ISSUE TITLE
Problems with ```2014 samle.csv``` file offered by TaxBrain

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#197]
The ```What is TaxBrain?``` section of the TaxBrain webapp offers people a ```[s]imple dummy dataset [2014]``` implying it can be used as input for the Tax-Calculator Records class.  I had several problems when trying to take up this offer:

(1) The embedded space in the file name ```2014 sample.csv``` caused havoc when I downloaded it on a Mac.  Maybe Windows users will have no problems, but it seems like it would be a good idea to replace the embedded space with a dash or underscore character.

(2) My browser balked at first over the size of the file which is 235 MB.  Why is it so big?  The ```puf.csv``` file used in TaxBrain production work is now only about 62 MB.

(3) And the real show-stopper is that this file **cannot** be used as input data for the Tax-Calculator Records class.   See the following error message generated by my attempt to use this (renamed) file:
````
iMac2:tax-calculator mrh$ python inctax.py ~/Downloads/2014-sample.csv 2014
Traceback (most recent call last):
  File "inctax.py", line 117, in <module>
    sys.exit(main())
  File "inctax.py", line 105, in main
    output_records=args.records)
  File "/Users/mrh/work/OSPC/tax-calculator/taxcalc/incometaxio.py", line 141, in __init__
    consider_imputations=False)
  File "/Users/mrh/work/OSPC/tax-calculator/taxcalc/records.py", line 288, in __init__
    self._read_data(data)
  File "/Users/mrh/work/OSPC/tax-calculator/taxcalc/records.py", line 476, in _read_data
    raise ValueError(msg.format(varname))
ValueError: Records data variable name recid not in VALID_READ_VARS
iMac2:tax-calculator mrh$ 
```

Offering something that will not work is guaranteed to get us off on the wrong foot with people new to OSPC and the Tax-Calculator.

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun

**Comment by GoFroggyRun** [comment]
@martinholmer: 

Thanks for prompt attention on this issue. 
Regarding some of your concerns:

(2) The  `2014 sample.csv` file has all the variables in `08 puf`, and `_numextra` that is used in TAXSIM. Thus there seem to be more variables (GW vs CX, as indexed by excel) in `2014 sample.csv` than `09 puf`. We, however,  definitely should figure out a way to compress the file.

(3) This might be the most critical concern regarding the input file: since `2014 sample.csv` is essentially the `a14` sample that was used for validation against TAXSIM, and thus contains the variable `_numextra`. This is actually a variable to be imputed, and the variable was now included as input. 
When testing the csv file through tax-calculator, the variable was manually added to the set `VALID_READ_VARS`, as a temporary solution. I'm actually wondering if there's any way to allow `_numextra` as input, maybe using a different variable name? And when inputed, the imputation process will be automatically skipped? Does this approach sounds reasonable? 
I'd expect the error to be resolved after fixing `_numextra`.

**Comment by MattHJensen** [comment]
I will mark the file as coming soon on taxbrain and remove the link until these issues are resolved.

**Comment by martinholmer** [comment]
The soon-to-be-available pure-CPS file for Tax-Calculator input will resolve this issue.
