### ISSUE TITLE
change start year UI?

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#273]
When someone changes the start year, a small text notice is displayed:

![image](https://cloud.githubusercontent.com/assets/8301092/16691755/e919e922-44fb-11e6-9ccb-599b268dc1ea.png)

I believe some users may not see this and are then surprised when the tables start from the default start year instead of the start year they wanted to set. 

@talumbau and @feenberg , what do you think about presenting a pop up that takes over the screen instead? It would need to say something like: "Changing the default start year will clear any tax law inputs you have made."..."Ok, go for it" or  "No, I want to keep the current start year".

**Comment by talumbau** [comment]
I don't think this would be difficult for @mistakevin. Assigning to him.

**Comment by feenberg** [comment]
On Fri, 8 Jul 2016, Matt Jensen wrote:

> 
> When someone changes the start year, a small text notice is displayed:
> 
> image
> 
> I believe some users may not see this and are then surprised when the tables start from the default
> start year instead of the start year they wanted to set.

OK, pretty subtle.

The popup-box should block further modifications to the main screen and 
should indicate that the default tax law parameters will change to the 
indicated year.

dan

**Comment by mistakevin** [comment]
Can do. Shouldn't be too hard.

**Comment by MattHJensen** [comment]
This feature is not currently working on TaxBrain. 

From @feenberg via email:

> In taxbrain I have been trying again to start the analysis in 2013, but the application ignores my request. There used to be a prompt when you selected 2013 - as far as I can tell the prompt is gone (good) but the analysis still starts in 2016. See
> 
>  http://www.ospc.org/taxbrain/edit/4870
> 
> Interestingly if you select "edit parameters" the URL changes to add year=2016 as a parameter. I tried changing the URL to 2013, didn't affect anything.
> 
> thanks
> 
> dan
> 

I have confirmed.

**Comment by mistakevin** [comment]
@MattHJensen @talumbau  It looks like the current deployed `taxbrain.js` is not the newest version
<img width="701" alt="screen shot 2016-08-11 at 5 24 36 pm" src="https://cloud.githubusercontent.com/assets/4411115/17607037/a67952da-5fe8-11e6-8de1-29af4f9c8880.png">
<img width="895" alt="screen shot 2016-08-11 at 5 24 45 pm" src="https://cloud.githubusercontent.com/assets/4411115/17607038/a67b01f2-5fe8-11e6-95c9-81182f982531.png">

**Comment by talumbau** [comment]
Looks like it's still loading the old static assets. I will try to upload the new ones and update this issue.

**Comment by talumbau** [comment]
There must be something I don't understand about `collectstatic`. For this Django app, if DEV_DEBUG is set to False, the `settings.py` is set to not use our static assets. In particular, one thing it does is that the command `python manage.py collectstatic` collects the static assets in `static/` and copies them to `STATIC_ROOT` which is `staticfiles/`. However, when I do that and then diff the directories `static/` and `staticfiles/`, they are quite different. So, that is bad because my assumption was always that I would get the complete set of files there.

The procedure would then be (assuming we have everything in `staticfiles/`) to execute the steps in [our wiki entry](https://github.com/OpenSourcePolicyCenter/webapp-public/wiki/Deploy-gzipped-CSS-and-javascript) on how to GZIP and deploy these static assets.

But that will not produce desired results if `staticfiles/` is wrong. So, before doing some kind of manual fix, maybe @mistakevin or @brendancol could explain where I'm doing wrong in what should happen with `collectstatic` and why there are difference between `static/` and `staticfiles/` after running it. Any ideas?

**Comment by talumbau** [comment]
this might be a reasonable answer:

http://stackoverflow.com/questions/17507843/django-storages-not-detecting-changed-static-files

if the timestamp if the newer file does not indicate that it is actually newer (which can happen through git pulls because I neglected to do the collecstatic operation in my branch) then it looks like I have to pass `collecstatic --clear` to make sure it actually updates the file in `staticfiles/`. I'll experiment with this on a test bucket in S3.

**Comment by talumbau** [comment]
This functionality is now restored. @mistakevin it would seem useful if there was some kind of "hook" that would either trigger on demand or when a PR is merged to master that would do as follows:

 - with DEBUG=False, run `python manage.py collectstatic --clear` so that all static content goes in to `staticfiles/`
 - execute some commands to gzip the CSS and JS files as described in the wiki entry
 - upload the resulting directory to the appropriate S3 bucket.

If this happened each time, we would never have to remember to do it. Is that feasible and/or a common solution to this problem?

**Comment by MattHJensen** [comment]
Thanks. I let Dan know.

**Comment by mistakevin** [comment]
@talumbau Yep, that is usually done by the CI technology, TravisCI or CircleCI. And Heroku can actually listen for Githooks as well, so a full deploy could happen with merge into Master.
