### ISSUE TITLE
few seconds calculation possible?

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#274]
@talumbau, some of our users have asked for near-instant results for a TaxBrain static run. I can definitely see the value, as I often use TaxBrain myself to titrate a revenue neutral reform. 

Do you think any of these strategies could provide near-instant results and not be too much trouble to implement? Each of them would require adding a new "quick-results" button onto the input page:

1) Calculate results on a random 2% sample of the tax data. 

2) Only calculate the first year revenue effect. 

3) only calculate the first year revenue effect on a 2% sample of tax data. 

cc @feenberg

**Comment by talumbau** [comment]
This is possible. I think we could reasonably get something in the 4-5 second range but doing one of these. I will do a test and see the timings on each idea and update this issue with results.

**Comment by talumbau** [comment]
An update here: I can reduce the one-year calculation time to about a third of its current time by making a couple of simple changes and reading in 2% of the data. There's a small change required in Tax-Calculator to make this happen, because the tax records are separate from the weights. I'm finishing that PR now, which has some tricky elements due to the variety of inputs one can give to the Records constructor.

**Comment by MattHJensen** [comment]
Thanks for the update @talumbau.

**Comment by talumbau** [comment]
With Tax-Calculator PR #844 I have done an unscientific timing and found that a TaxBrain calculation takes about 12 seconds from the time the user hits the button until the page renders. The drop-q calculation is really only about 2 seconds of that time. I could try to reduce the other 10 seconds which is related to the way we check for results on completed calculations. @MattHJensen or @feenberg, would a 12 second "speedy" calculation be good enough, or do you think that ~5 seconds should be the goal?

**Comment by feenberg** [comment]
On Wed, 3 Aug 2016, T.J. Alumbaugh wrote:

> 
> With Tax-Calculator PR #844 I have done an unscientific timing and found that a
> TaxBrain calculation takes about 12 seconds from the time the user hits the button
> until the page renders. The drop-q calculation is really only about 2 seconds of that
> time. I could try to reduce the other 10 seconds which is related to the way we check
> for results on completed calculations. @MattHJensen or @feenberg, would a 12 second
> "speedy" calculation be good enough, or do you think that ~5 seconds should be the
> goal?
>

I would hesitate to give advice without knowing where time was spent. Does 
the process read all 139K records in the speedy calculation, so the 
savings is only from doing only 1 year of results? I don't understand - 
2+10=12, so where is the time for actually calculating the tax for each 
taxpayer?

dan

**Comment by talumbau** [comment]
Before the request comes in, we have already read in the 139K records and prepared a "raw" dataset that is 2% of this data set. The actual calculation of this reduced dataset is about 1 second, and there's another ~1 second for the request to be received by the webserver, then given to the job execution system, then have a worker process spawned to do the work, and then store the result in the in-memory datastore (which is called "redis"). So, the 12 second breakdown is basically this: when submit is clicked, the loading page is set to check for the result every five seconds. The job is done within about 2, so then 3 seconds later the page checks for results and gets the answer that the job is ready. It immediately retrieves the result and stores it in the database. We reload the page at that point and another five second timer begins. After five seconds, it checks and finds that the answer is ready. It then takes about 2 seconds to load the results page because of all of the javascript and so forth on the page. So, now that I have dug into this, I think we can save five seconds just by redirecting to the results page as soon as the results are saved to the database (instead of reloading the wait page and waiting an additional five seconds). Let me make sure that works and I'll update this issue.

**Comment by talumbau** [comment]
By changing the refresh rate of checking the solution, I can get the total load time down to < 5 seconds. I'll put this in a PR. @feenberg and @MattHJensen do you want a button that says "Quick Calculation" next to the "Show me the results!" button?

**Comment by MattHJensen** [comment]
>5 seconds is great news! 

As a starting point, I'm fine with "Show me the results!" and a smaller "Quick calculation" below it. 

And then on the quick calculation page we should have some highlighted text at the top that says something like: 

"This Quick Calculation is for only one year and uses a 2% sample of the available data. Click here to recalculate the results for the 10-year budget window on the full dataset."

@feenberg, if you have any suggestions for the user interface, they would be very much appreciated.

**Comment by feenberg** [comment]
On Wed, 3 Aug 2016, T.J. Alumbaugh wrote:

> 
> By changing the refresh rate of checking the solution, I can get the total load time
> down to < 5 seconds. I'll put this in a PR. @feenberg and @MattHJensen do you want a
> button that says "Quick Calculation" next to the "Show me the results!" button?

Don't we have to say why it is quicker?

dan

**Comment by feenberg** [comment]
On Wed, 3 Aug 2016, Matt Jensen wrote:

>
>       5 seconds is great news!
> 
> As a starting point, I'm fine with "Show me the results!" and a smaller "Quick
> calculation" below it.
> 
> And then on the quick calculation page we should have some highlighted text at the top
> that says something like:
> 
> "This Quick Calculation is for only one year and uses a 2% sample of the available
> data. Click here to recalculate the results for the 10-year budget window on the full
> dataset."

Yes, telling people after the fact is fine - since they don't have to wait 
long to find out what they are getting. I take this info is not kept with 
the URL - so that someone clicking on the URL would get a recalculation 
with the full data?

dan

**Comment by MattHJensen** [comment]
> Don't we have to say why it is quicker? 

What do you think of "Fast results for 1 year on a 2% data sample"

**Comment by MattHJensen** [comment]
>  I take it this info is not kept with the URL - so that someone clicking on the URL would get a recalculation with the full data?

My expectation would be that the info *would* be kept with the URL. That way users could easily compare Fast calcs with the Full calcs.

**Comment by feenberg** [comment]
On Thu, 4 Aug 2016, Matt Jensen wrote:

>
>       I take it this info is not kept with the URL - so that someone clicking on
>       the URL would get a recalculation with the full data?
> 
> My expectation would be that the info would be kept with the URL. That way users could
> easily compare Fast calcs with the Full calcs.

Makes sense.

**Comment by talumbau** [comment]
closed via #299
