### ISSUE TITLE
'edit parameters' button broken

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#32]
The 'edit parameters' button from a TaxBrain results page does not return the user to an inputs page with the modified inputs pre-filled. This used to work but does not seem to anymore. 
cc @mistakevin @talumbau

**Comment by talumbau** [comment]
I think this was a consequence of keeping a lot of state out of the `session` in django. I'll defer to @mistakevin and @zrisher here, but it seemed like when we kept data in the `session`, you had the issue of going back two to TaxBrain two days later and having all of that info still in your browser, which was not good. However, if the user is at their results page, say `/taxbrain/555/` and then they hit the back button to go back to`/taxbrain/`, we would have to pull info from the session because we don't have a unique URL for the input page. Definitely seeking input here.

**Comment by talumbau** [comment]
@zrisher is it likely you could tackle this by the end of September?

**Comment by talumbau** [comment]
I have an idea here. By definition,"editing parameters" means that you have some pre-existing set of parameters that you have tried. This means that we can create some view like `/edit/{unique_id}/` to take you to. It will render just like the `/taxbrain`view, but will pre-populate based on the values in the database, bypassing all the weirdness of taking stuff out of the session. I think this is a cleaner answer. No JS and nothing stateful on the client side. I'll give it a shot.

**Comment by talumbau** [comment]
resolved via https://github.com/OpenSourcePolicyCenter/webapp-public/pull/49

**Comment by MattHJensen** [comment]
@talumbau, this is not working on https://ospc-taxes5.herokuapp.com/taxbrain/.

**Comment by MattHJensen** [comment]
From looking at #49, it seems like the "edit parameters" button on the results page might just need to be linked to the new view.

**Comment by MattHJensen** [comment]
This is working now. When I click "edit parameters" I see the changes I had made as dark black values rather than the lighter values: 

![image](https://cloud.githubusercontent.com/assets/8301092/10341825/5c22612e-6ce4-11e5-89e7-656064baae62.png)


Is it easy to make it display the "default value" underneath as well when the user returns to the page via the "edit parameters" button? I have to click in and out of the cell to get:

![image](https://cloud.githubusercontent.com/assets/8301092/10341846/70e37f08-6ce4-11e5-9c43-c561459cbc23.png)


cc @talumbau @zrisher

**Comment by talumbau** [comment]
resolved via https://github.com/OpenSourcePolicyCenter/webapp-public/pull/49
