### ISSUE TITLE
Default parameter values difficult to read

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#33]
@feenberg suggested that the default values for dollar items etc. in TaxBrain are difficult to read because of low contrast. 

Does anyone have any ideas for resolving this? Perhaps have default values one high-contrast color and user-modified values another high-contrast color? Actually, they could even be the same high contrast color and the only way to see something changed would be via the "default value: ___" that pops up underneath when you change something.

**Comment by feenberg** [comment]
On Sat, 5 Sep 2015, Matt Jensen wrote:

> 
> @feenberg suggested that the default values for dollar items etc. in
> TaxBrain are difficult to read because of low contrast.
> 
> Does anyone have any ideas for resolving this? Perhaps have default values
> one high-contrast color and user-modified values another high-contrast
> color? Actually, they could even be the same high contrast color and the
> only way to see something changed would be via the "default value: ___" that
> pops up underneath when you change something.

From feenberg@nber.org Sat Sep  5 17:51:30 2015
Date: Sat, 5 Sep 2015 17:51:28 -0400 (EDT)

**Comment by MattHJensen** [comment]
@feenberg, yes I see your point to use font rather than color. @zrisher, could you chime in on this one and then implement?

**Comment by zrisher** [comment]
In my mind, using anything besides a grey color to indicate placeholder text would be obscure. I'm having trouble finding a definitive source of UX best practice on this, but looking at major public internet sites I see the same approach everywhere - grey text, no text styling:

* https://www.google.com/preferences?hl=en#location - location box
* https://www.yahoo.com/ - quotes, scores, featured video boxes all along right sidebar
* https://www.facebook.com/ - search bar, Write a Comment
* https://twitter.com - search
* http://stackexchange.com/ - search bar

It's worth noting that browsers by default apply a style to placeholder text: with most it's a grey, with Firefox it's a black with opacity. Most normalization solutions overwrite moz to solid grey for consistency in case you do touch the input-placeholder pseudoelement. 

Google uses browser defaults directly. All the others above manually set the color, but in effect it's the same. Facebook and Twitter make the input text fairly dark when not focused and then a more normal amount of lightness when the input has focus.

If we believe that the current placeholders are too difficult to read, then I would suggest one or both of the following:
* Darken the grey currently used for placeholders
* Darken the placeholder when not in focus (like facebook and twitter)

Personally I'd prefer attempting the latter, but would like feedback on approach before doing that.

As a note to myself and @mistakevin, here's the [placeholder pseudoelement selectors](http://stackoverflow.com/questions/2610497/change-an-inputs-html5-placeholder-color-with-css).

**Comment by MattHJensen** [comment]
@zrisher, I believe the examples that you offer are not exact analogues to our input page. 

In the examples you gave, the placeholders tell you what to do or what type of text goes into the field: 

Google - "street address, zip code, city and state, county"
Facebook - "Search Facebook"
etc. 

Whereas in our case the placeholder text actually displays default values, and you have the option to overwrite it --- well, you do *need* to make at least one change.

Actually, the example from Zach the that I like to most is Twitter's "What's happening" box that uses high-contrast blue and then switches to black when you overwrite it.

What do you think about using a high contrast blue as default and then overwrite it with black typewriter font or italics? Note that we also have the "default value is..." that pops up underneath after a user has modified a value.

**Comment by MattHJensen** [comment]
@zrisher and @feenberg, does this make sense to you for the input page? 

>What do you think about using a high contrast blue as default and then overwrite it with black typewriter font or italics? Note that we also have the "default value is..." that pops up underneath after a user has modified a value. 

@zrisher, would this be difficult to implement?

**Comment by zrisher** [comment]
No, this wouldn't be difficult to implement. A few simple CSS rules with a standard selector.

As for if I believe it makes sense, in general with usability decisions I try to defer to user studies as much as possible, and in a case such as this where we don't have user studies I would defer to the practices of other websites that do have significant user studies (which has the added bonus of bringing our thinking in line with what's commonplace). In this case, I see it is unusual to have a different color for placeholder text other than grey with a black font, and especially unusual to style form input in a type or italic font to differentiate it from placeholders. 

So I would recommend trying the different coloration for placeholders if you think it makes sense for your user base, but if you'd like to use font / font style to differentiate I would recommend doing it to the placeholders instead of the input values.

**Comment by feenberg** [comment]
On Thu, 8 Oct 2015, zrisher wrote:

> 
> No, this wouldn't be difficult to implement. A few simple CSS rules with a standard
> selector.
> 
> As for if I believe it makes sense, in general with usability decisions I try to defer
> to user studies as much as possible, and in a case such as this where we don't have
> user studies I would defer to the practices of other websites that do have significant
> user studies (which has the added bonus of bringing our thinking in line with what's
> commonplace). In this case, I see it is unusual to have a different color for
> placeholder text other than grey with a black font, and especially unusual to style
> form input in a type or italic font to differentiate it from placeholders.

I don't think of it as "placeholder text" - the default values are 
important information and therefore should be readable. The use of gray 
text such "Last name"  in a name box is not really comparable since that 
is not acceptable input, whereas our default is actual input unless 
modified. Of course we need to show which values are modified, for which 
italic might be used. I would resist using color, since that would become 
invisible when printed.

dan

**Comment by zrisher** [comment]
I guess I tend to think of the term "placeholder text" in the technical sense - literally anything that shows up in a box before you type something - just because that's the html attribute name. My examples were for things that made use of this html attribute in any way, not only where it represented throw-away data. But regardless, @feenberg is reminding me that I'm pretty far removed from the expectations and needs of the target user group (I never would have thought about printing in black and white) and my examples don't apply so well because of that too.

I'm happy to do whatever you guys like, we can always try out a few different things.

**Comment by talumbau** [comment]
I think all are reasonably happy with default value text in TaxBrain input pages now.
