### ISSUE TITLE
CCC footer link to what is CCC drop down instead of ospc.org/about

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#333]
The footer link in CCC currently goes to www.ospc.org/about. It should go to the what is CCC drop down.

**Comment by PeterDSteinberg** [comment]
Fixed in #319.

**Comment by talumbau** [comment]
This link now takes you to the CCC drop down, which is better than before, but it does not "expand" to show the text that one gets when clicking "What is the Cost of Capital Calculator?" at the top. I am not sure how to construct such a URL, so that when someone clicks on the footer page, you go to the top and don't have to click "What is the Cost of Capital Calculator?" to make the text expand. I suspect it would not be a raw URL but something that called a JS function to make this behavior occur. Leaving open for now.

**Comment by MattHJensen** [comment]
To simplify, let's actually redirect this link back to www.ospc.org/about. The text should be, "Learn more about the Open Source Policy Center"

**Comment by brittainhard** [comment]
@MattHJensen @talumbau as a summary here, you want the link at the button of the `/CCC` page, which says `Learn more about Cost of Capital Calculator (B-Tax)` to link to the `/about` page, and you ant the text to say `Learn more about the Open Source Policy Center`? Right now it points to a non-existent endpoint called `http://localhost:8000/ccc/#taxbrainInfo`

**Comment by MattHJensen** [comment]
> you want the link at the button of the /CCC page, which says Learn more about Cost of Capital Calculator (B-Tax) to link to the /about page, and you want the text to say Learn more about the Open Source Policy Center? 

Correct. Thanks!

**Comment by brittainhard** [comment]
@MattHJensen would you want the same for the `/taxbrain` page?

**Comment by MattHJensen** [comment]
Ah, yes, good suggestion.
