### ISSUE TITLE
Application Error for PE model

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#374]
http://www.ospc.org/dynamic/behavior_results/330/
![image](https://cloud.githubusercontent.com/assets/8301092/19565754/fd0808e0-96b5-11e6-80a8-ed52803b0638.png)

**Comment by talumbau** [comment]
Although I can't get this to reproduce, the cause was apparently due to a hang on attempting to retrieve the results of the completed computation. After a period of polling of the worker node to see if the job is done, upon receiving a positive response, the server attempts to get the results. If this HTTP GET request (retrieving results) takes too long, the page will hang. There should be a time out set for this GET and a failure page displayed if the time out period is exceeded.

**Comment by brittainhard** [comment]
I'm seeing the error. I'll try TJ's approach to the problem.

**Comment by martinholmer** [comment]
Using TaxBrain v1.0.1 on 2017-08-16, this is no longer a problem.
