### ISSUE TITLE
Incorrect text in tooltip

### ISSUE THREAD

**Issue by brendancol** [OpenSourcePolicyCenter/webapp-public#397]
Notice the trailing punctuation /

<img width="393" alt="screen shot 2016-11-01 at 2 17 38 pm" src="https://cloud.githubusercontent.com/assets/433221/19903811/ff663a08-a03d-11e6-8b68-958b272b1b87.png">

**Comment by talumbau** [comment]
@brendancol, when we spoke about this initially, I thought that this had been fixed in Tax-Calculator already. However, when I look more closely at the current_law_policy.json file here:

https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/current_law_policy.json#L24

You can see that the `irs_ref` section does have this "Form , line ," text in it, which is weird. The text in that section is combined with the text in the `description` section to create the text for the tool tip. @MattHJensen, is this meant to be a placeholder for further info? If yes, perhaps we should create an issue on Tax-Calculator for fixing all of the "Form , line ," entries in current_law_policy.json.

**Comment by MattHJensen** [comment]
> If yes, perhaps we should create an issue on Tax-Calculator for fixing all of the "Form , line ," entries in current_law_policy.json.

I'll take care of this as part of resolving this issue.
