### ISSUE TITLE
CCC output - add economy-wide averages

### ISSUE THREAD

**Issue by salimfurth** [OpenSourcePolicyCenter/webapp-public#423]
As a user of the CCC, I would find economy-wide averages of the METTRs, METRs, etc, helpful in quickly interpreting the results of the CCC. It would be useful to have those for all corporate business, all non-corporate business and a weighted average of all business.

**Comment by MattHJensen** [comment]
@jdebacker, this is an enhancement rather than a bug, right?

**Comment by jdebacker** [comment]
@MattHJensen - this is kind of a bug fix.  I thought we had addressed it in Issue #388, but the PR referenced in that closing didn't seem to make this update.  I just made a comment over there before Salim posted this as a new issue.

I say 'kind of' since the other issue and PR still wouldn't over an overall business (corp + noncorp) rate.  I'm thinking we ignore that for now unless there's strong demand as it might take some rework of the tables (e.g. maybe a new column?).

cc @PeterDSteinberg

**Comment by talumbau** [comment]
@PeterDSteinberg is this done now with your latest PR?

**Comment by PeterDSteinberg** [comment]
This is fixed in #430

**Comment by jdebacker** [comment]
@PeterDSteinberg and @talumbau , this was not addressed in PR #430.  That PR corrected the results for industry and asset groupings, but did not add a row for the economy-wide average.

**Comment by PeterDSteinberg** [comment]
This is being fixed in #432 with corresponding [B-Tax PR 120](https://github.com/open-source-economics/B-Tax/pull/120) cc @talumbau @jdebacker

**Comment by jdebacker** [comment]
fixed w pr #432
