### ISSUE TITLE
Update TaxBrain input page based on new info from current_law_policy.json

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#436]
https://github.com/open-source-economics/Tax-Calculator/pull/1109 makes it so that current_law_policy.json fully specifies the content and layout of the TaxBrain input page to a human interpreter. A major update to the TaxBrain input page will be necessary when that PR is merged to reflect all of the new parameters available.

**Comment by MattHJensen** [comment]
This is ready now that open-source-economics/Tax-Calculator#1109 is merged. After the final b1 milestone is cleared, this should be the next big priority. 

@talumbau.

**Comment by brittainhard** [comment]
@MattHJensen is the idea here to manually update the inputs on the taxbrain page when the law policy changes?

**Comment by MattHJensen** [comment]
@brittainhard asked:

> is the idea here to manually update the inputs on the taxbrain page when the law policy changes?

Yes, that's the idea for now. 

After we have some experience with that process, we can make a decision about whether it is worth the effort to refactor the TaxBrain backend to automatically generate from current_law_policy.json. (see https://github.com/OpenSourcePolicyCenter/webapp-public/issues/435 for one approach we might consider at that time).

**Comment by brittainhard** [comment]
@MattHJensen looking at this more, it seems like we are adding another big feature -- the ability to set year parameters for inputs themselves, rather than just a blanket parameter set by the `Start Year` dropdown. Am I reading that correctly?

**Comment by MattHJensen** [comment]
@brittainhard asked:

> it seems like we are adding another big feature -- the ability to set year parameters for inputs themselves, rather than just a blanket parameter set by the Start Year dropdown. Am I reading that correctly?

No. The only changes should be adding some fields, reorganizing the ordering of the fields, renaming some sections and subsections, and adding new sections.

**Comment by brittainhard** [comment]
Ahh, okay. I was reading too much into that json file.

**Comment by MattHJensen** [comment]
Earlier @brittainhard asked:

> @MattHJensen is the idea here to manually update the inputs on the taxbrain page when the law policy changes?

To which I replied:

> Yes, that's the idea for now.
> 
> After we have some experience with that process, we can make a decision about whether it is worth the effort to refactor the TaxBrain backend to automatically generate from current_law_policy.json. (see #435 for one approach we might consider at that time).


I should clarify:

The values of the parameters should continue to be pulled over automatically as they are now. There should be no manual update for parameter values. 

The manual update will be when we add new parameters, rename them, or change their sections.

**Comment by brittainhard** [comment]
@MattHJensen @talumbau I'll give you an update on where I am.

I have created two functions that take the JSON from `taxcalc.Policy`, and parsed them into dictionaries that separate the fields based on the `section_1` attribute. These, in turn, are separated  into subcategories based on the `section_2` attribute. The result is a nested structure containing lists of the data. This keeps the order intact based on the data grabbed from the `Policy` class. All that is left for this part of the task is to change the templating to parse this new structure.

There is a problem on the taxcalc side, however. The lines [here](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/parameters.py#L217-L221) do not retain the order of `current_law_policy.json`. It is reading the JSON directly into a dictionary, which does not preserve order. Because of the way Python reads JSON, there is an order that is preserved each time the file is read, but it is not the order in which the data appears in `current_law_policy.json`

A fix to this would be to add the keyword argument `object_pairs_hook=OrderedDict` to the call to `json.load`. This would turn the data into an OrderedDict, keeping the order intact.

This fix would have to be made on the `taxcalc` side, because `taxbrain` reads the data straight from the `Policy` class.

Let me know what you think.

**Comment by talumbau** [comment]
good info @brittainhard. Let me try what you suggest quickly and see what it looks like on the `taxcalc` side.

**Comment by talumbau** [comment]
@brittainhard I just created this PR:
https://github.com/open-source-economics/Tax-Calculator/pull/1147

is that what you had in mind?

**Comment by brittainhard** [comment]
This was closed by #450
