### ISSUE TITLE
All previous CCC run urls display empty results. 

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#492]
![image](https://cloud.githubusercontent.com/assets/8301092/23378876/bfe057e8-fd02-11e6-8eed-2f0a8f96ae65.png)

I've checked a dozen or so and can't find one that shows up.

**Comment by brittainhard** [comment]
@MattHJensen I think whats going on here is that there have been significant changes in the application since that first ccc job. This problem could have something to do with either the application logic changing, or the database models changing. You will find this is the case with older taxbrain calculations, especially since we added the new form generation logic.

This problem goes deeper than a simple bugfix. A solution to this would require some investigation and planning, and some new features to ensure that older calculations are available. We can also simply remove older calculations before a certain date. If you'd like, I can put together a summary of my thoughts on this issue and potential solutions to this problem so we can have a starting point for  a larger discussion.

**Comment by PeterDSteinberg** [comment]
I agree this is a tough issue (to display all old results accurately), due to mix of serialized formats that we attempt to display when going back in time to an old model.  If there are specific old models we are interested in, we could do some poking around to see if we can modify the data to make them work, but I tend to agree with @brittainhard that we should just put a warning up on the results page if you viewing an old model.  We may want to have some logic like "do not show a /ccc model older than number X on the production app (put up a message redirecting them to /ccc input page), but attempt to show everything on test app" (and same thing for other models).

**Comment by MattHJensen** [comment]
Got it. I'd be happy if we just make sure we can get back all new results going forward. Is that doable?

**Comment by MattHJensen** [comment]
This is working again with recent runs, e.g., http://www.ospc.org/ccc/557/.  Closing.
