### ISSUE TITLE
Partial Equilibrium parameters not working in TB

### ISSUE THREAD

**Issue by GoFroggyRun** [OpenSourcePolicyCenter/webapp-public#512]
Under the same reform (available [here](http://www.ospc.org/taxbrain/edit/10418/?start_year=2017)), I implemented the partial equilibrium functionality in TB (available [here](https://www.ospc.org/dynamic/behavior_results/407/)), and it seem that this PE function is not working at all:

![screen shot 2017-03-16 at 2 45 13 pm](https://cloud.githubusercontent.com/assets/13324931/24015360/ad86183a-0a5e-11e7-9284-56c6e01537bb.png)

![screen shot 2017-03-16 at 2 47 30 pm](https://cloud.githubusercontent.com/assets/13324931/24015364/af896f06-0a5e-11e7-8862-2641e3738ad9.png)

Note that, from the two tables above, TB yields almost identical result with or without PE assumption, which is not the case for TC, nor dropQ local.

So my guess is that PE options are not being properly implemented in TB. 

cc @MattHJensen

**Comment by MattHJensen** [comment]
Confirmed. Thanks @GoFroggyRun

**Comment by GoFroggyRun** [comment]
It seem that, in the latest TB (test) release, taxable income and capital gains parameters under partial equilibrium sector are working just fine, while two parameters in Charitable Contributions section are not. 

The issue is that, when you input any valid parameter to any of the charitable contribution variable, the calculator will keep running. At least I wasn't able to finish any calculation involving charitable assumptions so far.

cc @MattHJensen  @brittainhard

**Comment by MattHJensen** [comment]
could you take a screenshot of the parameters that aren't working?

On Apr 3, 2017, at 3:08 PM, Sean.Wang <notifications@github.com<mailto:notifications@github.com>> wrote:


It seem that, in the latest TB (test) release, taxable income and capital gains parameters under partial equilibrium sector are working just fine, while two parameters in Charitable Contributions section are not.

The issue is that, when you input any valid parameter to any of the charitable contribution variable, the calculator will keep running. At least I wasn't able to finish any calculation involving charitable assumptions so far.

cc @MattHJensen<https://github.com/MattHJensen> @brittainhard<https://github.com/brittainhard>

**Comment by GoFroggyRun** [comment]
@MattHJensen :
![screen shot 2017-04-03 at 3 27 03 pm](https://cloud.githubusercontent.com/assets/13324931/24627226/0b2071e4-1882-11e7-8d6d-731a83b85b4b.png)

**Comment by MattHJensen** [comment]
We don't need to include those parameters for now. @brittainhard, is it trivial to drop them?

On Apr 3, 2017, at 3:27 PM, Sean.Wang <notifications@github.com<mailto:notifications@github.com>> wrote:


@MattHJensen<https://github.com/MattHJensen> :
[screen shot 2017-04-03 at 3 27 03 pm]<https://cloud.githubusercontent.com/assets/13324931/24627226/0b2071e4-1882-11e7-8d6d-731a83b85b4b.png>

**Comment by MattHJensen** [comment]
Just to be clear, the to dos here is:

- [ ] Remove the Charitable Contributions elasticities from the partial equilibrium page.

**Comment by brittainhard** [comment]
@MattHJensen I can remove them from the form. I'll push a fix.

**Comment by MattHJensen** [comment]
Resolved. Thanks @brittainhard and @GoFroggyRun
