### ISSUE TITLE
on homepage, "from the lab is off centered" 

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#71]
![image](https://cloud.githubusercontent.com/assets/8301092/10560142/e973b99a-74cf-11e5-9857-11068b679912.png)

cc @talumbau, @mistakevin, @zrisher

**Comment by mistakevin** [comment]
I tried to come up with a quick style fix, but it turned out to be a css rabbithole. I think this page should be laid out using the bootstrap grid, especially since development will look different than production due to flatblocks, we need to be as responsive as possible.

**Comment by zrisher** [comment]
I agree with @mistakevin, I think the positioning on this page needs some refactoring. Simply adding `text-align: center` to this element's style (or better yet the bootstrap class of `text-center` to the element) has no effect because of the relative positioning being applied to the surrounding elements to accomplish the background that stops halfway through the TaxBrain pane. If we forgo that background trick, fixing this is as simple as 

* remove `margin-bottom: 200px;` from the container `section.home-display`
* remove `bottom: -200px;` and `margin-top: -200px;` from `div.home-display-app` and add `margin-bottom: 50px`

![image](https://cloud.githubusercontent.com/assets/1958130/10803397/30f9e2be-7d7f-11e5-8323-d102949c1d94.png)

There's a lot of relative positioning going on in this page (and in the Taxbrain section I believe) because all of these pages had static content when we received the styles from the initial designers. Now that we've moved to a dynamic content model, more fully adopting bootstrap would make a lot of sense.

**Comment by MattHJensen** [comment]
>more fully adopting bootstrap would make a lot of sense. 

How big of a project is that and how would you recommend prioritizing it with ongoing work? 

>If we forgo that background trick, fixing this is as simple

In the meantime, I'd forgo aesthetics for the bug fix.

**Comment by zrisher** [comment]
> In the meantime, I'd forgo aesthetics for the bug fix.

See above, submitted a hotfix.

> How big of a project is that and how would you recommend prioritizing it with ongoing work?

Fairly large project as it involves rewriting a good chunk of the CSS, which brings with it the need to test on a lot of browsers and resolution sets. I would include it in a pass that fixes the dependency on `staticfiles` and removes the unused CSS we still have in the app. I would prioritize it after anything that directly affects the usability or functionality of the calculator pages.

**Comment by talumbau** [comment]
@johneo please read over this issue and let me know your thoughts. thanks!

**Comment by johneo** [comment]
If we can live with an increased gap, the header can be centered. Then we can circle back to the major refactoring.
<img width="1280" alt="taxbrain-h2-alignment-fix" src="https://cloud.githubusercontent.com/assets/501152/11046794/edc5736c-86f4-11e5-9e7a-9c7d71bae51d.png">
