### ISSUE TITLE
Bottom Radio button on growth parameters clears text next to button

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/webapp-public#90]
Described in detail here by @MattHJensen:

https://github.com/OpenSourcePolicyCenter/webapp-public/issues/87#issuecomment-151159872

**Comment by mistakevin** [comment]
The problem is in [paramradio.html](https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/templates/taxbrain/includes/params/inputs/paramradio.html#L36)
which generates this html:
<img width="444" alt="screen shot 2015-10-27 at 1 58 52 pm" src="https://cloud.githubusercontent.com/assets/4411115/10769281/4016f98e-7cb3-11e5-9336-847ce1d343cb.png">
I doubt this form is working correctly. This should probably be hotfixed soon.
@talumbau can you think of a quick fix here? If not, I can dig deeper.

**Comment by talumbau** [comment]
Is this not the proper default for a radio button? Anyway, I am responsible for the radio button but it's all pretty hokey because that radio button is not tied to the PersonalExemptionForm ModelForm. I think the real answer is a more mature Django form field or something from a JS toolkit because @MattHJensen mentioned that it would be desirous to have features like:

- if I start typing in one of the boxes, that radio button becomes selected
- if a radio button is selected and text is in the field next to it, if you click the other radio button, the text in the field next to the previously selected button disappears

there could be other useful interactions. The button does work in the sense that a selected button and selected text are propagated to the worker nodes and the "Edit Parameters" button will show the persisted state (if text is entered and a button is selected). If you could implement the two features listed above and have that make sense in some way with the Django ModelForm class, that would be great. H already implement a "growth_fixup" function to handle some of the ugliness here.

**Comment by MattHJensen** [comment]
Just want to chime in that the whole purpose of the radio button here is to keep the user from modifying both of the growth options at the same time. (An alternative, if it is easier, would be to just erase one when the user modifies the other and provide some sort of notification for why this happened.)
